services:
  - type: web
    name: firebird-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn main:app -c gunicorn.conf.py
    envVars:
      - key: DATABASE_PATH
        value: D:\sistemas\fcerta\DB\ALTERDB.ib
      - key: DATABASE_HOST
        value: 25.90.252.41
      - key: DATABASE_USERNAME
        value: SYSDBA
      - key: DATABASE_PASSWORD
        value: masterkey
      - key: DATABASE_PORT
        value: 3050
      - key: DATABASE_CHARSET
        value: WIN1252
      - key: PORT
        value: 10000